name: C++ CI

on:
  push:
    branches: [ master ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ master ]  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up CMake
        run: sudo apt-get install cmake g++  # Install CMake and g++

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..  # Configure the project

      - name: Build the project
        run: |
          cd build
          cmake --build .  # Build the project

      - name: Run Solutions
        run: |
          cd build
          ./exercises/ch1/p1/ch1_p1   # Run the executable
          # You can add more lines to run other exercises, e.g.,
          # ./exercise2_executable_name

