name: C++ CI with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code

      - name: Build Docker Image
        run: |
          docker build -t cpp-project .

      - name: Run Executables
        run: |
          docker run cpp-project ./build/exercises/ch1/p1/ch1_p1

